

NAME_MIN_CHARACTER = 4
NAME_MAX_CHARACTER = 64

NAME_REGEX = `^[A-z][A-z0-9-_]{${NAME_MIN_CHARACTER - 1},${NAME_MAX_CHARACTER - 1}}$`
NAME_REGEX_MINMAX = `^.{${NAME_MIN_CHARACTER},${NAME_MAX_CHARACTER}}$`
NAME_REGEX_LETTERFIRST = '^[A-z]'
NAME_REGEX_ALLOWEDCHARS = '^[a-zA-Z0-9_-]+$'


PASSWORD_MIN_CHARACTER = 8
PASSWORD_MAX_CHARACTER = 128

PASSWORD_REGEX = `^(?=.*[-_!#%@$])[a-zA-Z0-9-_!#%@$]{${PASSWORD_MIN_CHARACTER},${PASSWORD_MAX_CHARACTER}}$`
PASSWORD_REGEX_MINMAX = `^.{${PASSWORD_MIN_CHARACTER},${PASSWORD_MAX_CHARACTER}}$`
PASSWORD_REGEX_ALLOWEDCHARS = '[a-zA-Z0-9]+'
PASSWORD_REGEX_ALLOWEDSYMBOLS = '[-_!#%@$]+'





module.exports = {
	NAME_MIN_CHARACTER, 
	NAME_MAX_CHARACTER, 
	
	NAME_REGEX, 
	NAME_REGEX_MINMAX, 
	NAME_REGEX_LETTERFIRST, 
	NAME_REGEX_ALLOWEDCHARS, 


	PASSWORD_MIN_CHARACTER, 
	PASSWORD_MAX_CHARACTER, 

	PASSWORD_REGEX, 
	PASSWORD_REGEX_MINMAX, 
	PASSWORD_REGEX_ALLOWEDCHARS, 
	PASSWORD_REGEX_ALLOWEDSYMBOLS, 
}