

const MAX_LENGTH_PLAYER_NAME = +process.env.MAX_LENGTH_PLAYER_NAME || 50
const MAX_PLAYERS = +process.env.MAX_PLAYERS || 16
const MAX_COLUMNS = +process.env.MAX_COLUMNS || 10

const MAX_FINALSCORES_LIMIT = +process.env.MAX_FINALSCORES_LIMIT || 10





const REFRESH_TOKEN_SAMESITE = process.env.REFRESH_TOKEN_SAMESITE || 'None'
const REFRESH_TOKEN_SECURE = process.env.REFRESH_TOKEN_SECURE === 'true' || false





module.exports = {
	MAX_LENGTH_PLAYER_NAME, 
	MAX_PLAYERS, 
	MAX_COLUMNS, 

	MAX_FINALSCORES_LIMIT, 

	REFRESH_TOKEN_SAMESITE, 
	REFRESH_TOKEN_SECURE, 
}
