

const PORT = process.env.PORT || 10001

const MAX_LENGTH_PLAYER_NAME = +process.env.MAX_LENGTH_PLAYER_NAME || 50
const MAX_PLAYERS = +process.env.MAX_PLAYERS || 16
const MAX_COLUMNS = +process.env.MAX_COLUMNS || 10

const MAX_FINALSCORES_LIMIT = +process.env.MAX_FINALSCORES_LIMIT || 10





const REFRESH_TOKEN_SAMESITE = process.env.REFRESH_TOKEN_SAMESITE || 'None'
const REFRESH_TOKEN_SECURE = process.env.REFRESH_TOKEN_SECURE === 'true' || false
const REFRESH_TOKEN_MAX_AGE_IN_MINUTES = (parseInt(process.env.REFRESH_TOKEN_MAX_AGE_IN_MINUTES) || 24 * 60) * 60 * 1000





module.exports = {
	PORT, 
	
	MAX_LENGTH_PLAYER_NAME, 
	MAX_PLAYERS, 
	MAX_COLUMNS, 

	MAX_FINALSCORES_LIMIT, 

	REFRESH_TOKEN_SAMESITE, 
	REFRESH_TOKEN_SECURE, 
	REFRESH_TOKEN_MAX_AGE_IN_MINUTES, 
}
