

const PORT = process.env.PORT || 10001

const MAX_LENGTH_SESSION_NAME = +process.env.MAX_LENGTH_SESSION_NAME || 50
const MAX_LENGTH_PLAYER_NAME = +process.env.MAX_LENGTH_PLAYER_NAME || 50
const MAX_PLAYERS = +process.env.MAX_PLAYERS || 16
const MAX_COLUMNS = +process.env.MAX_COLUMNS || 10

const MAX_FINALSCORES_LIMIT = +process.env.MAX_FINALSCORES_LIMIT || 10





const REFRESH_TOKEN_SAMESITE = process.env.REFRESH_TOKEN_SAMESITE || 'None'
const REFRESH_TOKEN_SECURE = process.env.REFRESH_TOKEN_SECURE === 'true' || false
const REFRESH_TOKEN_MAX_AGE_IN_MINUTES = (parseInt(process.env.REFRESH_TOKEN_MAX_AGE_IN_MINUTES) || 24 * 60) * 60 * 1000




const DB_RETRIES = +process.env.DB_RETRIES || 60
const DB_RETRY_TIMEOUT_IN_SECONDS = +process.env.DB_RETRY_TIMEOUT_IN_SECONDS || 5





// ____________________ Email ____________________

const EMAIL_OF_ADMIN = process.env.EMAIL_OF_ADMIN
const EMAIL_SMTP_REPLYTOEMAIL = process.env.EMAIL_SMTP_REPLYTOEMAIL
const EMAIL_SMTP_HOST = process.env.EMAIL_SMTP_HOST
const EMAIL_SMTP_PORT = +process.env.EMAIL_SMTP_PORT
const EMAIL_SMTP_SSL = process.env.EMAIL_SMTP_SSL === 'true'
const EMAIL_SMTP_USERNAME = process.env.EMAIL_SMTP_USERNAME
const EMAIL_SMTP_PASSWORD = process.env.EMAIL_SMTP_PASSWORD





module.exports = {
	PORT, 
	
	MAX_LENGTH_SESSION_NAME, 
	MAX_LENGTH_PLAYER_NAME, 
	MAX_PLAYERS, 
	MAX_COLUMNS, 

	MAX_FINALSCORES_LIMIT, 

	REFRESH_TOKEN_SAMESITE, 
	REFRESH_TOKEN_SECURE, 
	REFRESH_TOKEN_MAX_AGE_IN_MINUTES, 

	DB_RETRIES, 
	DB_RETRY_TIMEOUT_IN_SECONDS, 

	EMAIL_OF_ADMIN, 
	EMAIL_SMTP_REPLYTOEMAIL, 
	EMAIL_SMTP_HOST, 
	EMAIL_SMTP_PORT, 
	EMAIL_SMTP_SSL, 
	EMAIL_SMTP_USERNAME, 
	EMAIL_SMTP_PASSWORD, 
}
